@host = http://localhost:4000
@email = brett@email.com
@password = 123456

# @name register
POST {{ host }}/users HTTP/1.1
content-type: application/json

{
    "display_name": "Brett Wiltshire",
    "email": "{{ email }}",
    "password": "{{ password }}",
    "image": "https://i.imgur.com/uSEgddG.png"
}

###

# @name login
POST {{ host }}/users/login HTTP/1.1
content-type: application/json

{
    "email": "{{ email }}",
    "password": "{{ password }}"
}

###

# @name list_users
GET {{ host }}/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.token }}

###

# @name get_user
GET {{ host }}/users/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.token }}

###

# @name get_me
GET {{ host }}/users/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.token }}

###

# @name delete_me
DELETE {{ host }}/users/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.token }}

###

# @name create_post
POST {{ host }}/posts HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "title": "My Blog Post",
    "content": "My content"
}

###

# @name list_posts
GET {{ host }}/posts HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.token }}

###

# @name search_posts
GET {{ host }}/posts?q=New content HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.token }}

###

# @name get_post
GET {{ host }}/posts/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.token }}

###

# @name update_post
PUT {{ host }}/posts/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "title": "New title",
    "content": "New content"
}

###

# @name delete_post
DELETE {{ host }}/posts/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{ login.response.body.token }}

###

